on: push
name: Deploy Pipeline CI/CD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: oder2701
        password: Concol1986*-16

    - name: Build and push image
      run: |
        docker build -t powerbi:latest .
        docker push oder27:latest/powerbi:latest

    - name: SSH into K3s server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.1.11
        username: root
        password: Root123
        run: |
          kubectl apply -f powerbi.yaml
